language: ruby
sudo: false
cache: bundler
rvm:
# - ruby-head (see as below)
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
env:
  global:
    - CODECLIMATE_REPO_TOKEN=f88e6216112f3039c2ceb879c813ad95b99e4ac13413a7fc104dc176eb7c63bb
  matrix:
    - RAILS_VERSION=3.2
    - RAILS_VERSION=4.0
    - RAILS_VERSION=4.1
    - RAILS_VERSION=4.2
    - RAILS_VERSION=5.0
matrix:
  allow_failures:
  fast_finish: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cdc790028864bf9cbc44
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
