language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - jruby-head
  - jruby
  - jruby-19mode
env:
  global:
    - CODECLIMATE_REPO_TOKEN=f88e6216112f3039c2ceb879c813ad95b99e4ac13413a7fc104dc176eb7c63bb
    - JRUBY_OPTS='--dev -J-Xmx1024M'
  matrix:
    - RAILS_VERSION=3.2
    - RAILS_VERSION=4.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cdc790028864bf9cbc44
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
