language: ruby
sudo: false
cache: bundler
after_success:
  - '[ "${TRAVIS_JOB_NUMBER#*.}" = "1" ] && bundle exec codeclimate-test-reporter'
rvm:
# - ruby-head (see as below)
  - 2.4.1
  - 2.3.4
env:
  global:
    - CODECLIMATE_REPO_TOKEN=f88e6216112f3039c2ceb879c813ad95b99e4ac13413a7fc104dc176eb7c63bb
  matrix:
    - RAILS_VERSION=4.2
matrix:
  allow_failures:
  fast_finish: true
